version: "3.8"

services:
  influxdb:
    image: influxdb:1.8.10-alpine
    restart: unless-stopped
    ports:
      - 8086:8086
    env_file:
      - .env
  grafana:
    image: grafana/grafana:9.3.8-ubuntu
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: true
    depends_on:
      - influxdb
    env_file:
      - .env
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
