apiVersion: 1

datasources:
  - name: InfluxDB-InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: $DOCKER_INFLUXDB_INIT_USERNAME
    database: $DOCKER_INFLUXDB_INIT_BUCKET
    jsonData:
      httpHeaderName1: 'Authorization'
      httpMode: GET
    secureJsonData:
      httpHeaderValue1: Token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      password: $DOCKER_INFLUXDB_INIT_PASSWORD
    editable: true
  - name: InfluxDB-Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: $DOCKER_INFLUXDB_INIT_USERNAME
    jsonData:
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
      organization: $DOCKER_INFLUXDB_INIT_ORG
      version: Flux
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    editable: true
